site_title: "Next Level Jiu-Jitsu Sherman"
site_description: "World-class Brazilian Jiu-Jitsu training for all ages and skill levels in Sherman, Texas. Located inside Midway Mall."
logo: "/assets/logo.svg"
phone: ""
email: ""
social_media:
  facebook: ""
  instagram: ""
  youtube: ""

